OSPF: 
    process_id: "1"
    rid: "1.1.1.1"
    redistributing:
        - "redistribute connected subnets"
        - "redistribute eigrp 100 subnets"
    networks:
        - "19.19.19.0 0.0.0.255 area 0"
        - "20.20.20.0 0.0.0.255 area 0"
        - "185.10.10.0 0.0.0.255 area 0"
