---
dmvpn:
    tunnel_ip: 172.16.1.4 255.255.255.0
    type: Spoke
    source:
        int: gig2
        ip: 204.0.0.02 255.255.255.0
    hub:
        tunnel_ip: 172.16.1.1

vrf:
    peer_ip: 204.0.0.1